<?php
/**
 * @file
 * A description of what your module does.
 */

/**
 * Implements hook_block_info().
 */
function icasus_block_info() {
  $blocks['icasus'] = array(
    'info' => t('Icasus data'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;

}

/**
 * Implements hook_block_configure().
 */
function icasus_block_configure($delta = '') {
  $form = array();

  switch ($delta) {
    case'icasus':
      $form['icasus_url'] = array(
        '#type' => 'textfield',
        '#title' => t('URL Icasus'),
        '#description' => t('url for request'),
        '#default_value' => variable_get('block_icasus_url'),
      );
      break;
  }
  return $form;
}

/**
 * Implements hook_block_save().
 */
function icasus_block_save($delta = '', $edit = array()) {
  switch ($delta) {
    case 'icasus':
      variable_set('block_icasus_url', $edit['icasus_url']);
      break;
  }
}

/**
 * Implements hook_block_view().
 */
function icasus_block_view($delta = '') {
  $block = array();
  $block['subject'] = t('Icasus data');
  $block['content'] = t('<p>&nbsp;</p><p>&nbsp;</p><div class="rtecenter"><div 
  style="display:inline-block; margin:10px;"><a href="https://icasus3.us
  .es/index.php?page=plan_listar&amp;id_entidad=14" style="color:#404040;" 
target="_blank"><i aria-hidden="true" class="fa fa-book fa-4x">' .
    variable_get("icasus_data_1") . '</i><br 
    /><strong>Planes Estratégicos</strong></a></div><div style="display:inline-block; margin:10px;"><a 
    href="https://icasus3.us.es/index.php?page=proceso_listar&amp;
    id_entidad=14" style="color:#404040;" target="_blank"><i 
aria-hidden="true" class="fa fa-cogs  fa-4x">' . variable_get('icasus_data_2')
    . '</i><br /><strong>Procesos</strong></a></div><div style="display: 
    inline-block; margin:10px;"><a 
    href="https://icasus3.us.es/index.php?page=indicador_listar&amp;
    id_entidad=14" style="color:#404040;" target="_blank"><i aria-hidden="true" 
    class="fa fa-tachometer fa-4x">' . variable_get('icasus_data_3') .
    '</i><br />
<strong>Indicadores/Datos</strong></a></div><div style="display:inline-block; margin:10px;"><a 
href="https://icasus3.us.es/index.php?page=cuadro_listar&amp;id_entidad=14" 
style="color:#404040;" target="_blank"><i aria-hidden="true" class="fa fa-th fa-4x">' .
    variable_get('icasus_data_4')
    . '</i><br />
<strong>Cuadros de mando</strong></a></div></div>');
  return $block;
}

/**
 * Implements hook_cron().
 */
function icasus_cron() {
  $request = drupal_http_request(variable_get
  ('block_icasus_url'));
  $json_response = drupal_json_decode($request->data);
  $i = 0;
  foreach ($json_response as $data) {
    variable_set("icasus_data_" . $i, $data);
    $i = $i + 1;
  }

}